"""New migration

Revision ID: 1d82e83bb5b4
Revises: 08376c73cf01
Create Date: 2023-09-21 06:00:56.391966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d82e83bb5b4'
down_revision = '08376c73cf01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
