"""New migration

Revision ID: 5658e7084e10
Revises: 5809e85a4180
Create Date: 2023-10-03 09:40:09.572861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5658e7084e10'
down_revision = '5809e85a4180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('course_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'course_name')
    # ### end Alembic commands ###
