"""New migration

Revision ID: 5809e85a4180
Revises: 1d82e83bb5b4
Create Date: 2023-09-21 06:05:47.819689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5809e85a4180'
down_revision = '1d82e83bb5b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('pic', sa.String(), nullable=True))
    op.drop_column('questions', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('questions', 'pic')
    # ### end Alembic commands ###
