"""New Migration

Revision ID: ebfd17a6e56d
Revises: b8dce79f9ec8
Create Date: 2023-07-25 03:03:13.427029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfd17a6e56d'
down_revision = 'b8dce79f9ec8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('explanation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'explanation')
    # ### end Alembic commands ###
