"""New migration

Revision ID: ec73035095ca
Revises: 5658e7084e10
Create Date: 2023-10-03 10:31:03.735220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec73035095ca'
down_revision = '5658e7084e10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('intro', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'intro')
    # ### end Alembic commands ###
